name: qiqstr
description: "Easy to use Nostr client"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.1+0

environment:
    sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
    flutter:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    shared_preferences: ^2.3.2
    isar: ^3.1.0+1
    isar_flutter_libs: ^3.1.0+1
    path_provider: ^2.1.5
    path: ^1.9.0
    gallery_saver_plus: ^3.2.9
    uuid: ^4.5.1
    cached_network_image: ^3.4.0
    flutter_secure_storage: ^9.2.4
    logging: ^1.3.0
    build_runner: ^2.4.13
    video_player: ^2.9.2
    smooth_page_indicator: ^1.2.0+3
    base32: ^2.1.3
    photo_view: ^0.15.0
    url_launcher: ^6.3.1
    flutter_linkify: ^6.0.0
    flutter_riverpod: ^2.6.1
    provider: ^6.1.2
    file_picker: ^10.2.0
    bolt11_decoder: ^1.0.2
    dotted_border: ^3.1.0
    nostr_nip19: ^0.1.0
    auto_size_text: ^3.0.0
    collection: ^1.19.1
    http: ^1.4.0
    crypto: ^3.0.6
    kmbal_ionicons: ^1.0.0
    bech32: ^0.2.2
    flutter_svg: ^2.0.10+1
    html: ^0.15.4
    carbon_icons: ^0.0.1+2
    rxdart: ^0.28.0
    screenshot: ^3.0.0
    share_plus: ^12.0.0
    get_it: ^9.0.5
    intl: ^0.20.2
    bip39: ^1.0.6
    bip32: ^2.0.0
    flutter_native_splash: ^2.4.7
    google_fonts: ^6.2.1
    ndk: ^0.6.0
    webview_flutter: ^4.13.0
    web_socket_channel: ^3.0.1
    go_router: ^14.6.2
    qr_flutter: ^4.1.0
    qr_code_scanner: ^1.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    # The "flutter_lints" package below contains a set of recommended lints to
    # encourage good coding practices. The lint set provided by the package is
    # activated in the `analysis_options.yaml` file located at the root of your
    # package. See that file for information about deactivating specific lint
    # rules and activating additional ones.
    flutter_lints: ^6.0.0
    isar_generator: ^3.1.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/

flutter_native_splash:
    color: "#ffffff"             
    color_dark: "#000000"        
    
    image: assets/main_icon_uni.png  
    image_dark: assets/main_icon_uni_dark.png
    
    fullscreen: false
    
    android_12:
        color: "#ffffff"
        color_dark: "#000000"
        
        image: assets/main_icon_uni.png
        image_dark: assets/main_icon_uni_dark.png
        
        icon_background_color: "#ffffff"
        icon_background_color_dark: "#000000"
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/to/font-from-package
